name: Indigenous connect frontend CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]  

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Copy environment files
      run: |
        cp ~/env/frontend/.env ./
        cp ~/env/frontend/.env.local ./

    - name: Install dependencies with pnpm
      run: pnpm install

    - name: Build project
      run: pnpm run build

    - name: Debug Build Logs
      run: cat .next/build-manifest.json || echo "Build manifest not found"

    - name: Restart the app using pm2 
      run: pm2 restart ic-frontend
